sudo: false # route your build to the container-based infrastructure for a faster build
language: ruby
rvm:
  - 2.2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_script:
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site
